import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path


def plot_from_csv():
    # Define path to the history file generated by step_05
    BASE_PATH = Path(r"E:\Medicine\XRAY-decease-classification\XRAY-ML-system")
    HISTORY_PATH = BASE_PATH / "ml" / "models" / "member1_resnet18" / "eda" / "training_history.csv"

    if not HISTORY_PATH.exists():
        print(f"Error: {HISTORY_PATH} not found. Run step_05_train_model.py first!")
        return

    # Load the data
    df = pd.read_csv(HISTORY_PATH)

    epochs = df['epoch']
    train_acc = df['train_acc']
    val_acc = df['val_acc']
    train_loss = df['train_loss']
    val_loss = df['val_loss']

    plt.figure(figsize=(14, 6))

    # Plot 1: Accuracy
    plt.subplot(1, 2, 1)
    plt.plot(epochs, train_acc, 'bo-', label='Training Accuracy', linewidth=2)
    plt.plot(epochs, val_acc, 'ro-', label='Validation Accuracy', linewidth=2)
    plt.title('Training & Validation Accuracy', fontsize=14)
    plt.xlabel('Epochs', fontsize=12)
    plt.ylabel('Accuracy (%)', fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)

    # Plot 2: Loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs, train_loss, 'bo-', label='Training Loss', linewidth=2)
    plt.plot(epochs, val_loss, 'ro-', label='Validation Loss', linewidth=2)
    plt.title('Training & Validation Loss (Focal Loss)', fontsize=14)
    plt.xlabel('Epochs', fontsize=12)
    plt.ylabel('Loss Value', fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)

    plt.suptitle(f"Model Performance Summary: {HISTORY_PATH.parent.name}", fontsize=16)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])

    # Save the plot as an image in the model folder
    plt.savefig(HISTORY_PATH.parent / "performance_curves.png")
    print(f"Plot saved to: {HISTORY_PATH.parent / 'performance_curves.png'}")
    plt.show()


if __name__ == "__main__":
    plot_from_csv()